### ISSUE TITLE
Question regarding dockerregistry param in ALOpsDockerCreate

### ISSUE THREAD

**Issue by gntpet** [HodorNV/ALOps#448] opened 2021-11-03 22:13 UTC
Hey Devops gurus, 

Could you please shed some light regarding ALOpsDockerCreate & dockerregistry param usage. 

**Excepect behaviour**
When dockerregistry is specified, I expect ALOpsDockerCreate to check my docker registry and pull image if it exists. If image does not exist, it should create image and push it to registery.

Is it supposed to work like that?

Best Regards, 
Gintautas

**Comment by waldo1001** [comment] 2021-11-04 09:24
It's indeed supposed to work like that.  

What doesn't work?

**Comment by gintuoklis** [comment] 2021-11-04 09:38
Then i guess we have a bug :)

Here's the code snippet i used to create container:
```
- task: ALOpsDockerCreate@1
  condition: in(variables['getEnvName.envName'], 'mvbctesting')
  displayName: 'ALOPS - Create Docker Image' 
  inputs:
    artifactversion: '18.4'
    artifactcountry: 'w1'
    artifacttype: OnPrem
    includetesttoolkit: true
    #forcecreateimage: true
    licensefile: "$(Agent.TempDirectory)/license/fin.flf"
    myscripts: $(Build.SourcesDirectory)\AL_scripts\AdditionalSetup.ps1
    dockerregistry: 'k3devops.azurecr.io'
    dockerusername: $(dtr_username)
    dockerpassword: $(dtr_password)
    imageprefix: 'mvbc'

```
and here's the output. As you can see, it couldn't find an image and did not even tried to create one. Just finished the task with *** Docker Create Succeeded.



```
ModuleType Version    Name                                ExportedCommands                                             
---------- -------    ----                                ----------------                                             
Script     2.0.16     BcContainerHelper                   {Add-FontsToBcContainer, Add-GitToAlProjectFolder, Backup-...




*** Get Artifact Url for Version [18.4] / Country [w1] / Type [OnPrem]: Latest
"Get-BCArtifactUrl" 
Name                           Value                                                                                   
----                           -----                                                                                   
select                         Latest                                                                                  
version                        18.4                                                                                    
type                           OnPrem                                                                                  
country                        w1                                                                                      



*** Artifact Url: [https://bcartifacts.azureedge.net/onprem/18.4.28601.29139/w1]
*** Build new Image based on [https://bcartifacts.azureedge.net/onprem/18.4.28601.29139/w1]
*** Artifact Type   : [onprem]
*** Artifact Version: [18.4.28601.29139]
*** Artifact Country: [w1]
*** OS: [2019]
*** OS version: [10.0.17763.2237]
*** Image Template: [%IMAGE_PREFIX%:%ARTIFACT_TYPE%-%ARTIFACT_VERSION%-%ARTIFACT_COUNTRY%-%OS_VERSION%-%OS_LTSC%]
*** ImageName: [***.azurecr.io/mvbc:onprem-18.4.28601.29139-w1-10.0.17763.2237-ltsc2019]
*** Set Pipeline variable $(ALOPS_BC_IMAGE) = '***.azurecr.io/mvbc:onprem-18.4.28601.29139-w1-10.0.17763.2237-ltsc2019'
Error: No such image: ***.azurecr.io/mvbc:onprem-18.4.28601.29139-w1-10.0.17763.2237-ltsc2019
*** Pull Docker Image: ***.azurecr.io/mvbc:onprem-18.4.28601.29139-w1-10.0.17763.2237-ltsc2019
*** Login into docker: ***.azurecr.io
U: 8
P: 32
WARNING! Your password will be stored unencrypted in C:\a\_temp\DockerConfig_1635976911112\config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
Error response from daemon: manifest for ***.azurecr.io/mvbc:onprem-18.4.28601.29139-w1-10.0.17763.2237-ltsc2019 not found: manifest unknown: manifest tagged by "onprem-18.4.28601.29139-w1-10.0.17763.2237-ltsc2019" is not found
*** Pull Docker Image: ***.azurecr.io/mvbc:onprem-18.4.28601.29139-w1-10.0.17763.2237-ltsc2019 [OK]

*** Logout docker: ***.azurecr.io
Removing login credentials for ***.azurecr.io
*** Docker Create Succeeded.
*** Cleanup VSTS Environment: True
Finishing: ALOPS - Create Docker Image
```

**Comment by waldo1001** [comment] 2021-11-04 10:19
Ok, this looks indeed like unexpected behavior, so we'll need to set up a repro for this and test it.. .

**Comment by gintuoklis** [comment] 2021-11-10 17:14
hey @waldo1001, 
did you manage to find something?

**Comment by waldo1001** [comment] 2021-11-10 23:29
Yes, it's fixed in our next version.  
This version contains a few new features that are not done yet, so ... we try to publish it this week..

**Comment by waldo1001** [comment] 2022-02-10 10:01
Can you confirm this is fixed?  
If not - could you provide a simple repro-yaml?

**Comment by waldo1001** [comment] 2022-03-15 11:02
Will close issue since there hasn't been any feedback. Please re-open if it's still an issue after re-install.

**Closed by waldo1001** 2022-03-15 11:02 UTC
Labels: part of an upcoming release, feedback
