### ISSUE TITLE
ALOpsDockerStart - Cannot find an overload for "GetObjectsForNativeVariants"

### ISSUE THREAD

**Issue by martonsagi** [HodorNV/ALOps#40] opened 2019-10-14 20:37 UTC
Today I ran into the following issue when starting a build. Last week I did not get this kind of error.

```
##[section]Starting: ALOpsDockerStart
==============================================================================
Task         : ALOps Docker Start
Description  : ALOps Docker Start
Version      : 1.424.710
Author       : Hodor
Help         : Start Business Central docker container.
==============================================================================
*** Importing required PS-Functions
##[error]Cannot find an overload for "GetObjectsForNativeVariants" and the argument count: "1".
##[section]Finishing: ALOpsDockerStart
```

[Build #89 details](https://dev.azure.com/dynasist/ATDD.TestManager/_build/results?buildId=89&view=logs&jobId=12f1170f-54f2-53f3-20dd-22fc7dff55f9&taskId=1a344f33-b4bf-58c7-e117-aec5ab142303&lineStart=1&lineEnd=11&colStart=1&colEnd=39)

[YAML file](https://github.com/dynasist/ATDD.TestManager/blob/master/azure-pipelines.yml)

Build Agent:
* Self-hosted Windows Server 2019 1809 17763.805 (OS Up-to-date)
* Docker: 18.09.4, build c3516c43ef
* ALOps: v1.424.710

Docker is confirmed to be operational on the agent as it has other BC15 instances up and running.

**Comment by waldo1001** [comment] 2019-10-17 12:57
Hi @martonsagi ,

we have seen this with other people before.  Thing is: we are not using that function, nor are we loading any module that has this function.  Why powershell attempts to use it, is not because of ALOps.

It has always been solved by "reinstalling the agent machine".  I know this is not what you want to hear, but I'm afraid this is out of our hands.. .

I just rechecked our ALOps code - there is absolutely no reference to that function.. .

**Comment by martonsagi** [comment] 2019-10-17 22:33
Hi @waldo1001 ,

Thanks for the info.

> It has always been solved by "reinstalling the agent machine". I know this is not what you want to hear, but I'm afraid this is out of our hands.. 

Unfortunately, this is something I can't afford to do in the near future.

Well, whatever it may be, the exception might be thrown in the mysterious `...\1.425.834\ps_modules\alops\923a3c49-e87f-4e7f-b7ee-889556369715.ps1`

All I could find out is that Powershell Obfuscation uses [`Marshal.SecureStringToGlobalAllocAnsi`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.securestringtoglobalallocansi?view=netframework-4.8), which is the very same class where [`GetObjectsForNativeVariants`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getobjectfornativevariant?view=netframework-4.8) resides. There might be a connection..

With the updated ALOps v1.425.834, I'm getting a bit different error for the same DockerStart/DockerRemove steps:
```
##[error]Exception calling "GetObjectForNativeVariant" with "1" argument(s): "Specified OLE variant is invalid."
```

**Comment by waldo1001** [comment] 2019-10-18 06:05
We are investigating on our side as well .. .  Sorry for this inconvenience :(.

**Comment by waldo1001** [comment] 2019-10-18 08:10
We are thinking windows updates - trying to find a machine where we can replicate the problem (we have about 17 machines that run smoothly .. but none of them have automatic windows updates to ensure stability icw docker and such.. .

Every release of ALOps goes through a multitude of different builds (about 25 different scenarios) to ensure stability .. none of them failed.

But we have now 2 reports of the same issue - so this needs to be addressed.  We might have to remove the obfuscation or do it different.  

Will keep you posted!

**Comment by waldo1001** [comment] 2019-10-18 09:30
Hi @martonsagi ,

I was able to replicate the problem - it was caused by a windows update.  Though - restarting my machine resolved it.  Can you try to restart the machine?

**Comment by martonsagi** [comment] 2019-10-18 11:18
Hi @waldo1001 ,

Thanks, I've tried the restart option (although the VM is stopped at night), still getting the `"Specified OLE variant is invalid."` error.
Indeed, I have auto-updates turned on, as the agent VM is a multi-purpose host for other docker images and .NET pipelines, etc.., so I'd like to keep the OS up-to-date.

While I can't reinstall that VM with above issues, creating a clean agent VM reserved for ALOps sounds a way forward. Will get back to you with the results.

**Comment by waldo1001** [comment] 2019-10-18 11:22
I just replicated the problem by the windows update - and "fixed" it simply with a restart.  The next 15 builds have run just fine.
I also had another customer that had this problem, and also fixed after restart.

We will look into it however, since as you mentioned it's because of the obfuscation, not te ALOps business logic.  And we should not depend on the OS as much .. .  It will take time, however.  I hope the new VM will fix your issues.

**Comment by martonsagi** [comment] 2019-10-18 14:39
There's always an edge-case with me. :)

New VM worked out much better, now I'm receiving errors related to BC15 Test Apps, but that's a story for another day. Other than that the ALOps steps seem to be running free of strange issues.

Thanks for the help, I'm one step closer to solution!

**Comment by waldo1001** [comment] 2019-11-13 15:20
@martonsagi , can we close this issue?

**Comment by martonsagi** [comment] 2019-11-13 15:59
Yes, I'm fine with using a clean VM, so it's solved for me. Thanks!

**Closed** 2019-11-13 16:02 UTC
Labels: investigate

**Comment by DanielGoehler** [comment] 2022-05-11 20:07
Patching servers is a high priority for us as we try to minimize all attack vectors on our servers so we don't get encrypted and blackmailed with ransomware. 

On the last two Microsoft Patch Days (04/12/2022 and 05/10/2022), I reinstalled the build agent and all went well. That's a relatively easy way to do it in PowerShell: 
```PowerShell
cd c:\agent
.\config remove --unattended --auth PAT --token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
cd ..
cmd.exe /c "rd /s /q C:\agent" #Somehow deleting via PowerShell doesn't work
md C:\agent
cd agent
Add-Type -AssemblyName System.IO.Compression.FileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory("$HOME\Downloads\vsts-agent-win-x64-2.202.1.zip", "$PWD")
.\config --unattended --url https://dev.azure.com/company --auth PAT --token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --pool BCBuildAgents --agent $env:computername --acceptTeeEula --runAsService --windowsLogonAccount domain\agent-user --windowsLogonPassword password
```

[More Info](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#unattended-config)
