### ISSUE TITLE
ALOpsAppSign - Cannot bind argument to parameter 'Path' because it is null.

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#224] opened 2020-10-19 22:03 UTC
**Describe the bug**
Previous to the ALOpsAppCompiler@2 version, we had setup to compile / sign steps, one for the app and one for the test app. Switching to v2 seems like ALOpsAppCompiler is able to compile both app and test app at once, which is fine!

However, when signing the apps, I'm getting following error

`Cannot bind argument to parameter 'Path' because it is null.`

It resolves to the test app, while it should in fact Sign both apps.
I've default the artifact_path (used to refer to $(System.ArtifactsDirectory))

**the used yaml**

```
steps:
- task: ALOpsAppCompiler@2
  displayName: 'Compile'
  enabled: ${{ parameters.enabled }}
  inputs:
    artifactversion: $(currentBuild)
    artifacttype: 'OnPrem' # 'Sandbox' ?
    artifactcountry: $(country)
    appversiontemplate: '?.?.?.*'
    alcodeanalyzer: ${{ parameters.al_analyzer }}
    failonwarnings: ${{ parameters.failed_on_warnings }}

- task: ALOpsAppSign@1
  displayName: 'Sign'
  enabled: ${{ parameters.enabled }}
  continueOnError: true
  inputs:
    pfx_path: $(pfx_file)
    pfx_password: 'xxx'
    publish_artifact: false 
```

**the output**

Compile

```
2020-10-19T21:53:44.8621127Z ##[section]Starting: Compile
2020-10-19T21:53:44.8709207Z ==============================================================================
2020-10-19T21:53:44.8709450Z Task         : ALOps App Compiler
2020-10-19T21:53:44.8709647Z Description  : Compile AL Extension(s) for Business Central
2020-10-19T21:53:44.8709854Z Version      : 2.0.1864
2020-10-19T21:53:44.8710004Z Author       : Hodor
2020-10-19T21:53:44.8710199Z Help         : Compile Business Central extension(s) from AL code.
2020-10-19T21:53:44.8710457Z ==============================================================================
2020-10-19T21:53:45.5542501Z ******************************************************************************
2020-10-19T21:53:45.5547008Z *** ALOps v2 - Preview                                                     ***
2020-10-19T21:53:45.5551976Z ******************************************************************************
2020-10-19T21:53:45.5556234Z *** Importing required ALOps-Functions
2020-10-19T21:53:45.9073760Z *** For documentation, please visit   : https://www.alops.be/documentation
2020-10-19T21:53:45.9075643Z 
2020-10-19T21:53:46.1557281Z *** ALOps License:
2020-10-19T21:53:46.1574724Z   * Licensed To: Navitrans
2020-10-19T21:53:46.1576736Z 
2020-10-19T21:53:46.1605776Z *** ALOps Show Variables: false
2020-10-19T21:53:46.2806030Z *** Memory Status: 27.92/31.84 (87.69% Free)
2020-10-19T21:53:46.3393237Z *** Importing required Task-Functions
2020-10-19T21:53:47.0849883Z 
2020-10-19T21:53:47.1003461Z *** Artifact Type   : [OnPrem]
2020-10-19T21:53:47.1009893Z *** Artifact Version: [16.3]
2020-10-19T21:53:47.1014845Z *** Artifact Country: [w1]
2020-10-19T21:53:47.1019696Z *** AL Source Path  : [C:\DockerInstallation\Agent\_work\4\s]
2020-10-19T21:53:47.1024583Z *** AL Cache Path   : [C:\DockerInstallation\Agent\_work\4\s]
2020-10-19T21:53:47.1026248Z 
2020-10-19T21:53:47.1038542Z 
2020-10-19T21:53:47.1155675Z *** Default Working Folder: C:\DockerInstallation\Agent\_work\4\s
2020-10-19T21:53:47.1162275Z *** Artifact Folder       : C:\DockerInstallation\Agent\_work\4\a
2020-10-19T21:53:47.1166371Z *** Agent Tool Folder     : C:\DockerInstallation\Agent\_work\_tool
2020-10-19T21:53:47.1171125Z *** Agent Temp Folder     : C:\DockerInstallation\Agent\_work\_temp
2020-10-19T21:53:47.1174313Z 
2020-10-19T21:53:47.1198859Z *** Resolving Path: [C:\DockerInstallation\Agent\_work\4\s]
2020-10-19T21:53:47.1242930Z *** AL Source Folder      : C:\DockerInstallation\Agent\_work\4\s
2020-10-19T21:53:47.1248157Z *** Resolving Path: [C:\DockerInstallation\Agent\_work\4\s]
2020-10-19T21:53:47.1255375Z *** AL Cache Folder       : C:\DockerInstallation\Agent\_work\4\s
2020-10-19T21:53:47.1258542Z 
2020-10-19T21:53:47.1268612Z *** Check BcContainerHelper
2020-10-19T21:53:47.2368680Z *** Load BcContainerHelper
2020-10-19T21:53:48.6822921Z 
2020-10-19T21:53:48.6830116Z ModuleType Version    Name                                ExportedCommands                                             
2020-10-19T21:53:48.6833701Z ---------- -------    ----                                ----------------                                             
2020-10-19T21:53:48.6850860Z Script     1.0.9      BcContainerHelper                   {Add-FontsToBcContainer, Add-GitToAlProjectFolder, Backup-...
2020-10-19T21:53:48.6853776Z 
2020-10-19T21:53:48.6915459Z ##[command]"Get-BCArtifactUrl" 
2020-10-19T21:53:48.6916165Z Name                           Value                                                                                   
2020-10-19T21:53:48.6916516Z ----                           -----                                                                                   
2020-10-19T21:53:48.6917344Z select                         Latest                                                                                  
2020-10-19T21:53:48.6917829Z version                        16.3                                                                                    
2020-10-19T21:53:48.6918312Z type                           OnPrem                                                                                  
2020-10-19T21:53:48.6919560Z country                        w1                                                                                      
2020-10-19T21:53:48.6919739Z 
2020-10-19T21:53:48.6919801Z 
2020-10-19T21:53:48.6919961Z  -select: Latest -version: 16.3 -type: OnPrem -country: w1
2020-10-19T21:53:48.9220588Z *** Platform: c:\bcartifacts.cache\onprem\16.3.14085.14238\platform
2020-10-19T21:53:48.9248051Z *** Localisation: c:\bcartifacts.cache\onprem\16.3.14085.14238\w1
2020-10-19T21:53:48.9317886Z *** BC Management DLL: C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\LegacyDlls\program files\Microsoft Dynamics NAV\160\RoleTailored Client\Microsoft.Dynamics.Nav.Management.dll
2020-10-19T21:53:48.9463113Z *** BC App Management DLL: C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\LegacyDlls\program files\Microsoft Dynamics NAV\160\RoleTailored Client\Microsoft.Dynamics.Nav.Apps.Management.dll
2020-10-19T21:53:48.9580303Z *** Get [*.app] and [app.json] files recursive from [C:\DockerInstallation\Agent\_work\4\s]
2020-10-19T21:53:48.9807368Z *** Found [2] files.
2020-10-19T21:53:48.9812822Z *** Extract App detail from [C:\DockerInstallation\Agent\_work\4\s\App\app.json]
2020-10-19T21:53:48.9863391Z *** Extract App detail from [C:\DockerInstallation\Agent\_work\4\s\Test\app.json]
2020-10-19T21:53:49.0401063Z *** Starting Batch compile of Apps:
2020-10-19T21:53:49.0423422Z   * C:\DockerInstallation\Agent\_work\4\s\App
2020-10-19T21:53:49.0428989Z   * C:\DockerInstallation\Agent\_work\4\s\Test
2020-10-19T21:53:49.0439337Z *** Start Compiling: [C:\DockerInstallation\Agent\_work\4\s\App]
2020-10-19T21:53:49.0709018Z *** Get App Information
2020-10-19T21:53:49.0728068Z *** Loading Json Object: [C:\DockerInstallation\Agent\_work\4\s\App\app.json]
2020-10-19T21:53:49.0740343Z   * Id         : 25f1cbff-7ee3-4fe1-aa54-400ab34da0b4
2020-10-19T21:53:49.0746021Z   * Publisher  : Navitrans
2020-10-19T21:53:49.0751907Z   * Name       : Core
2020-10-19T21:53:49.0757117Z   * Description: Navitrans 365 Core
2020-10-19T21:53:49.0845086Z *** Retaining original [Major] from version (?.0.0.0)
2020-10-19T21:53:49.0867274Z *** Retaining original [Minor] from version (0.?.0.0)
2020-10-19T21:53:49.0872465Z *** Retaining original [Build] from version (0.0.?.0)
2020-10-19T21:53:49.0884297Z *** Setting Managed App Version [C:\DockerInstallation\Agent\_work\4\s\App\app.json] =>  16.3.0.4927
2020-10-19T21:53:49.0964507Z *** VSCode Settings: [C:\DockerInstallation\Agent\_work\4\s\App\.vscode\settings.json]
2020-10-19T21:53:49.0972750Z *** VSCode-Settings json found.
2020-10-19T21:53:49.0979856Z *** Loading Json Object: [C:\DockerInstallation\Agent\_work\4\s\App\.vscode\settings.json]
2020-10-19T21:53:49.1016664Z *** Using Ruleset: [C:\DockerInstallation\Agent\_work\4\s\App\.vscode\nvt.ruleset.json]
2020-10-19T21:53:49.1067946Z ##[command]"Get-BCArtifactUrl" 
2020-10-19T21:53:49.1069667Z Name                           Value                                                                                   
2020-10-19T21:53:49.1070452Z ----                           -----                                                                                   
2020-10-19T21:53:49.1070833Z select                         Latest                                                                                  
2020-10-19T21:53:49.1071181Z version                        16.3                                                                                    
2020-10-19T21:53:49.1071493Z type                           OnPrem                                                                                  
2020-10-19T21:53:49.1071960Z country                        w1                                                                                      
2020-10-19T21:53:49.1072356Z 
2020-10-19T21:53:49.1072409Z 
2020-10-19T21:53:49.1072462Z 
2020-10-19T21:53:49.1383854Z *** Platform: c:\bcartifacts.cache\onprem\16.3.14085.14238\platform
2020-10-19T21:53:49.1400687Z *** Localisation: c:\bcartifacts.cache\onprem\16.3.14085.14238\w1
2020-10-19T21:53:49.2159894Z *** Get Platform Apps [84]
2020-10-19T21:53:49.2177922Z *** Get Localised Apps [0]
2020-10-19T21:53:49.2191013Z *** Loaded [84] Platform Apps
2020-10-19T21:53:49.2201418Z *** Get Build Apps [0]
2020-10-19T21:53:49.2206909Z *** AL Cache: [C:\DockerInstallation\Agent\_work\4\s]
2020-10-19T21:53:49.2290062Z *** Loaded [0] AL Apps
2020-10-19T21:53:49.2444242Z *** VSIX Path: C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage.vsix
2020-10-19T21:53:49.2495350Z *** ALC Path: C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\alc.exe
2020-10-19T21:53:49.2524964Z *** AL Language Version: 5.0.288712
2020-10-19T21:53:49.2541282Z *** App To Build: [C:\DockerInstallation\Agent\_work\4\a\Navitrans_Core_16.3.0.4927_OnPrem_16.3_w1.app]
2020-10-19T21:53:49.2547858Z *** Checking for Assemblies in App
2020-10-19T21:53:49.2619819Z *** Add Windows Assembly Path [C:\Windows\assembly]
2020-10-19T21:53:49.3140993Z *** Adding Mock assemblies [C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\Test Assemblies\Mock Assemblies]
2020-10-19T21:53:49.3788864Z *** Adding Add-In assemblies [C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\LegacyDlls\program files\Microsoft Dynamics NAV\160\RoleTailored Client\Add-ins]
2020-10-19T21:53:49.3798783Z *** Adding Add-In assemblies [C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ServiceTier\program files\Microsoft Dynamics NAV\160\Service\Add-ins]
2020-10-19T21:53:49.3826139Z *** Searching CodeCop: CodeCop
2020-10-19T21:53:49.3963268Z *** Codecop found: C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.CodeCop.dll
2020-10-19T21:53:49.4241207Z *** Searching CodeCop: UICop
2020-10-19T21:53:49.4241602Z *** Codecop found: C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.UICop.dll
2020-10-19T21:53:49.4467554Z *** Searching CodeCop: AppSourceCop
2020-10-19T21:53:49.4467973Z *** Codecop found: C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.AppSourceCop.dll
2020-10-19T21:53:49.4698465Z *** Copy BC Artifact dependencies
2020-10-19T21:53:49.7585156Z *** Copy Project Artifact dependencies
2020-10-19T21:53:49.7591007Z *** Copy Build Artifacts
2020-10-19T21:53:49.7603657Z *** Start ALC.EXE / Compile AL Extension
2020-10-19T21:53:49.7627033Z ##[command]& alc.exe /packagecachepath:"C:\DockerInstallation\Agent\_work\4\s\App\.ALOPSCache" /project:"C:\DockerInstallation\Agent\_work\4\s\App" /out:"C:\DockerInstallation\Agent\_work\4\a\Navitrans_Core_16.3.0.4927_OnPrem_16.3_w1.app" /fullpaths /assemblyprobingpaths:C:\Windows\assembly,C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\Test Assemblies\Mock Assemblies,C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\LegacyDlls\program files\Microsoft Dynamics NAV\160\RoleTailored Client\Add-ins,C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ServiceTier\program files\Microsoft Dynamics NAV\160\Service\Add-ins /analyzer:"C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.CodeCop.dll","C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.UICop.dll","C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.AppSourceCop.dll" /ruleset:"C:\DockerInstallation\Agent\_work\4\s\App\.vscode\nvt.ruleset.json"
2020-10-19T21:53:55.5962817Z *** AL Compiler Exit Code: 0
2020-10-19T21:53:55.6001460Z *** Set Pipeline variable $(ALOPS_COMPILE_ARTIFACT) = 'C:\DockerInstallation\Agent\_work\4\a\Navitrans_Core_16.3.0.4927_OnPrem_16.3_w1.app'
2020-10-19T21:53:55.6073413Z *** Start processing compile results.
2020-10-19T21:53:55.6726853Z Core: \App\extensionsPermissionSet.xml(1,1): info AL1027: The file at location '\App\extensionsPermissionSet.xml' matches the definition for 'PermissionSet'.
2020-10-19T21:53:55.6785192Z 
2020-10-19T21:53:55.6787213Z 
2020-10-19T21:53:55.6789290Z 
2020-10-19T21:53:55.6841292Z AlertCode Line RelativePath                     File                        AlertSource AlertMessage                   
2020-10-19T21:53:55.6844806Z --------- ---- ------------                     ----                        ----------- ------------                   
2020-10-19T21:53:55.6850988Z AL1027    1    \App\extensionsPermissionSet.xml extensionsPermissionSet.xml AL Compiler The file at location 'C:\Doc...
2020-10-19T21:53:55.6851380Z 
2020-10-19T21:53:55.6870134Z 
2020-10-19T21:53:55.6931936Z *** Set Pipeline variable $(ALOPS_COMPILE_LOG) = 'C:\DockerInstallation\Agent\_work\4\s\Navitrans_Core_16.3.0.4927_OnPrem_16.3_w1.log'
2020-10-19T21:53:55.7306172Z *** Uploading App as Build-Artifact
2020-10-19T21:53:55.7751243Z *** Start Compiling: [C:\DockerInstallation\Agent\_work\4\s\Test]
2020-10-19T21:53:55.7751697Z *** Get App Information
2020-10-19T21:53:55.7751898Z *** Loading Json Object: [C:\DockerInstallation\Agent\_work\4\s\Test\app.json]
2020-10-19T21:53:55.7752126Z   * Id         : cdfba696-cc0d-4eb6-8834-9c85d8d141e8
2020-10-19T21:53:55.7752293Z   * Publisher  : Navitrans
2020-10-19T21:53:55.7752466Z   * Name       : Core-Test
2020-10-19T21:53:55.7752620Z   * Description: Navitrans Core Components
2020-10-19T21:53:55.7752804Z *** Retaining original [Major] from version (?.0.0.0)
2020-10-19T21:53:55.7752988Z *** Retaining original [Minor] from version (0.?.0.0)
2020-10-19T21:53:55.7753176Z *** Retaining original [Build] from version (0.0.?.0)
2020-10-19T21:53:55.7753418Z *** Setting Managed App Version [C:\DockerInstallation\Agent\_work\4\s\Test\app.json] =>  16.3.0.4927
2020-10-19T21:53:55.7753707Z *** VSCode Settings: [C:\DockerInstallation\Agent\_work\4\s\Test\.vscode\settings.json]
2020-10-19T21:53:55.7753918Z *** VSCode-Settings json found.
2020-10-19T21:53:55.7754127Z *** Loading Json Object: [C:\DockerInstallation\Agent\_work\4\s\Test\.vscode\settings.json]
2020-10-19T21:53:55.7754404Z *** Using Ruleset: [C:\DockerInstallation\Agent\_work\4\s\Test\.vscode\nvt.ruleset.json]
2020-10-19T21:53:55.7754615Z ##[command]"Get-BCArtifactUrl" 
2020-10-19T21:53:55.7755223Z Name                           Value                                                                                   
2020-10-19T21:53:55.7755597Z ----                           -----                                                                                   
2020-10-19T21:53:55.7755928Z select                         Latest                                                                                  
2020-10-19T21:53:55.7756248Z version                        16.3                                                                                    
2020-10-19T21:53:55.7756568Z type                           OnPrem                                                                                  
2020-10-19T21:53:55.7756895Z country                        w1                                                                                      
2020-10-19T21:53:55.7757082Z 
2020-10-19T21:53:55.7757145Z 
2020-10-19T21:53:55.7757206Z 
2020-10-19T21:53:55.7768654Z *** Platform: c:\bcartifacts.cache\onprem\16.3.14085.14238\platform
2020-10-19T21:53:55.7776523Z *** Localisation: c:\bcartifacts.cache\onprem\16.3.14085.14238\w1
2020-10-19T21:53:55.8831802Z *** Get Platform Apps [84]
2020-10-19T21:53:55.8844133Z *** Get Localised Apps [0]
2020-10-19T21:53:55.8850846Z *** Loaded [84] Platform Apps
2020-10-19T21:53:55.8879648Z *** Get Build Apps [1]
2020-10-19T21:53:55.8885847Z *** AL Cache: [C:\DockerInstallation\Agent\_work\4\s]
2020-10-19T21:53:55.8994854Z *** Loaded [0] AL Apps
2020-10-19T21:53:55.9209387Z *** VSIX Path: C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage.vsix
2020-10-19T21:53:55.9231392Z *** ALC Path: C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\alc.exe
2020-10-19T21:53:55.9265056Z *** AL Language Version: 5.0.288712
2020-10-19T21:53:55.9277301Z *** App To Build: [C:\DockerInstallation\Agent\_work\4\a\Navitrans_Core-Test_16.3.0.4927_OnPrem_16.3_w1.app]
2020-10-19T21:53:55.9283458Z *** Checking for Assemblies in App
2020-10-19T21:53:55.9298412Z *** Add Windows Assembly Path [C:\Windows\assembly]
2020-10-19T21:53:55.9963920Z *** Adding Mock assemblies [C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\Test Assemblies\Mock Assemblies]
2020-10-19T21:53:56.0653140Z *** Adding Add-In assemblies [C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\LegacyDlls\program files\Microsoft Dynamics NAV\160\RoleTailored Client\Add-ins]
2020-10-19T21:53:56.0658550Z *** Adding Add-In assemblies [C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ServiceTier\program files\Microsoft Dynamics NAV\160\Service\Add-ins]
2020-10-19T21:53:56.0664703Z *** Searching CodeCop: CodeCop
2020-10-19T21:53:56.0793346Z *** Codecop found: C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.CodeCop.dll
2020-10-19T21:53:56.1338837Z *** Searching CodeCop: UICop
2020-10-19T21:53:56.1339254Z *** Codecop found: C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.UICop.dll
2020-10-19T21:53:56.1596675Z *** Searching CodeCop: AppSourceCop
2020-10-19T21:53:56.1597062Z *** Codecop found: C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.AppSourceCop.dll
2020-10-19T21:53:56.1859650Z *** Copy BC Artifact dependencies
2020-10-19T21:53:56.6169533Z *** Copy Project Artifact dependencies
2020-10-19T21:53:56.6173754Z *** Copy Build Artifacts
2020-10-19T21:53:56.6209442Z *** Start ALC.EXE / Compile AL Extension
2020-10-19T21:53:56.6215588Z ##[command]& alc.exe /packagecachepath:"C:\DockerInstallation\Agent\_work\4\s\Test\.ALOPSCache" /project:"C:\DockerInstallation\Agent\_work\4\s\Test" /out:"C:\DockerInstallation\Agent\_work\4\a\Navitrans_Core-Test_16.3.0.4927_OnPrem_16.3_w1.app" /fullpaths /assemblyprobingpaths:C:\Windows\assembly,C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\Test Assemblies\Mock Assemblies,C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\LegacyDlls\program files\Microsoft Dynamics NAV\160\RoleTailored Client\Add-ins,C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ServiceTier\program files\Microsoft Dynamics NAV\160\Service\Add-ins /analyzer:"C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.CodeCop.dll","C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.UICop.dll","C:\bcartifacts.cache\onprem\16.3.14085.14238\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.AppSourceCop.dll" /ruleset:"C:\DockerInstallation\Agent\_work\4\s\Test\.vscode\nvt.ruleset.json"
2020-10-19T21:54:05.1783894Z *** AL Compiler Exit Code: 0
2020-10-19T21:54:05.1789541Z *** Set Pipeline variable $(ALOPS_COMPILE_ARTIFACT) = 'C:\DockerInstallation\Agent\_work\4\a\Navitrans_Core-Test_16.3.0.4927_OnPrem_16.3_w1.app'
2020-10-19T21:54:05.1800506Z *** Start processing compile results.
2020-10-19T21:54:05.2157501Z *** Uploading App as Build-Artifact
2020-10-19T21:54:05.2579629Z ##[section]Async Command Start: Add Build Tag
2020-10-19T21:54:05.2579919Z Build '4927' has following tags now: AL.Analyzer.CodeCop, AL.Analyzer.UICop, AL.Analyzer.AppSourceCop
2020-10-19T21:54:05.2580119Z ##[section]Async Command End: Add Build Tag
2020-10-19T21:54:05.2580595Z ##[section]Async Command Start: Add Build Tag
2020-10-19T21:54:05.2580845Z Build '4927' has following tags now: AL.Analyzer.UICop, AL.Analyzer.AppSourceCop
2020-10-19T21:54:05.2581099Z ##[section]Async Command End: Add Build Tag
2020-10-19T21:54:05.2581518Z ##[section]Async Command Start: Add Build Tag
2020-10-19T21:54:05.2581742Z Build '4927' has following tags now: AL.Analyzer.AppSourceCop
2020-10-19T21:54:05.2581905Z ##[section]Async Command End: Add Build Tag
2020-10-19T21:54:05.2582320Z ##[section]Async Command Start: Upload Artifact
2020-10-19T21:54:05.2582504Z Uploading 1 files
2020-10-19T21:54:05.2582597Z File upload succeed.
2020-10-19T21:54:05.2582820Z Upload 'C:\DockerInstallation\Agent\_work\4\a\Navitrans_Core_16.3.0.4927_OnPrem_16.3_w1.app' to file container: '#/10650955/Navitrans.Base'
2020-10-19T21:54:05.2583050Z Associated artifact 6518 with build 4927
2020-10-19T21:54:05.2583184Z ##[section]Async Command End: Upload Artifact
2020-10-19T21:54:05.2583610Z ##[section]Async Command Start: Add Build Tag
2020-10-19T21:54:05.2583870Z Build '4927' has following tags now: AL.Analyzer.CodeCop, AL.Analyzer.UICop, AL.Analyzer.AppSourceCop
2020-10-19T21:54:05.2584340Z ##[section]Async Command End: Add Build Tag
2020-10-19T21:54:05.2585044Z ##[section]Async Command Start: Add Build Tag
2020-10-19T21:54:05.2585299Z Build '4927' has following tags now: AL.Analyzer.CodeCop, AL.Analyzer.UICop, AL.Analyzer.AppSourceCop
2020-10-19T21:54:05.2585488Z ##[section]Async Command End: Add Build Tag
2020-10-19T21:54:05.2586357Z ##[section]Async Command Start: Add Build Tag
2020-10-19T21:54:05.2586659Z Build '4927' has following tags now: AL.Analyzer.CodeCop, AL.Analyzer.UICop, AL.Analyzer.AppSourceCop
2020-10-19T21:54:05.2586851Z ##[section]Async Command End: Add Build Tag
2020-10-19T21:54:05.2587271Z ##[section]Async Command Start: Upload Artifact
2020-10-19T21:54:05.2587396Z Uploading 1 files
2020-10-19T21:54:05.4850105Z File upload succeed.
2020-10-19T21:54:05.4850419Z Upload 'C:\DockerInstallation\Agent\_work\4\a\Navitrans_Core-Test_16.3.0.4927_OnPrem_16.3_w1.app' to file container: '#/10650955/Navitrans.Base'
2020-10-19T21:54:05.4850721Z Associated artifact 6518 with build 4927
2020-10-19T21:54:05.4850897Z ##[section]Async Command End: Upload Artifact
2020-10-19T21:54:05.4851821Z ##[section]Finishing: Compile
```

Sign

```
2020-10-19T21:54:05.4941002Z ##[section]Starting: Sign
2020-10-19T21:54:05.5027018Z ==============================================================================
2020-10-19T21:54:05.5027178Z Task         : ALOps App Sign
2020-10-19T21:54:05.5027307Z Description  : CodeSign an AL Extension for Business Central
2020-10-19T21:54:05.5027426Z Version      : 1.435.1864
2020-10-19T21:54:05.5027528Z Author       : Hodor
2020-10-19T21:54:05.5027656Z Help         : Codesign Business Central extension with .pfx.
2020-10-19T21:54:05.5027811Z ==============================================================================
2020-10-19T21:54:06.3173620Z *** Validate configuration
2020-10-19T21:54:06.5322553Z *** For documentation, please visit   : https://www.alops.be/documentation
2020-10-19T21:54:06.5325572Z 
2020-10-19T21:54:06.7911841Z *** ALOps License:
2020-10-19T21:54:06.7930199Z   * Licensed To: Navitrans
2020-10-19T21:54:06.7933135Z 
2020-10-19T21:54:06.7956214Z *** ALOps Show Variables: false
2020-10-19T21:54:06.8589837Z *** Memory Status: 27.93/31.84 (87.73% Free)
2020-10-19T21:54:06.9073667Z *** Importing required PS-Functions
2020-10-19T21:54:07.2593633Z *** Dynamic resolve App file.
2020-10-19T21:54:07.2600049Z *** Scanning [System.DefaultWorkingDirectory].
2020-10-19T21:54:07.2834938Z *** Scanning [System.ArtifactsDirectory].
2020-10-19T21:54:07.2860161Z *** Scanning [Pipeline.Workspace].
2020-10-19T21:54:07.3199062Z *** Multiple App files found with filter [*.app].
2020-10-19T21:54:07.3242320Z   * C:\DockerInstallation\Agent\_work\4\a\Navitrans_Core_16.3.0.4927_OnPrem_16.3_w1.app
2020-10-19T21:54:07.3246848Z   * C:\DockerInstallation\Agent\_work\4\a\Navitrans_Core-Test_16.3.0.4927_OnPrem_16.3_w1.app
2020-10-19T21:54:07.3279151Z *** Resolved App File: [Navitrans_Core-Test_16.3.0.4927_OnPrem_16.3_w1.app].
2020-10-19T21:54:07.5340216Z *** Fetching App to Sign in [C:\DockerInstallation\Agent\_work\4\s] with filter [*.app]
2020-10-19T21:54:07.6594407Z ##[error]Cannot bind argument to parameter 'Path' because it is null.
2020-10-19T21:54:08.2798765Z ##[section]Finishing: Sign
```

**Comment by waldo1001** [comment] 2020-10-20 13:40
We'll need to repro this scenario to come up with a fix .. working on it!

(see, this is why we provide previews ;-))

**Comment by fvet** [comment] 2020-10-20 14:10
This is why we are testing on a separate branch 😉

**Comment by jcoe-nvt** [comment] 2020-10-20 14:20
@waldo1001 
> Did you try with the "nav_artifact_app_filter" param?

Not sure how we would use the filter parameter, as this is same problem as in #227

**Comment by jcoe-nvt** [comment] 2020-11-18 15:20
@waldo1001 
If no filters are used AlOpsAppSign resolves to the correct app, but immediatly after the resolve, it's fetching the wrong app:
![image](https://user-images.githubusercontent.com/49404625/99548625-23b9cd80-29b9-11eb-9ea2-a512909cc81f.png)

If filters are used for ALOpsAppSign it still resolves to the correct app, but then it tries to fetch app again with applied filter, but in the wrong directory. It seems that resolving the app isn't used for fetching the app to sign:
![image](https://user-images.githubusercontent.com/49404625/99549197-afcbf500-29b9-11eb-8e5e-b42d98d9aa61.png)

If I add an additional powershell step to move my apps from ArtifactDirectory to WorkingDirectory it seems that resolve and fetch do result in the same app-file:
![image](https://user-images.githubusercontent.com/49404625/99549442-eefa4600-29b9-11eb-994e-4210a24ad559.png)

**Comment by fvet** [comment] 2020-11-26 15:30
@waldo1001 I've seen quit some issues tagged with 'part of upcoming release'.
Have you been able to simulate the above? If not, we could try to provide a repro using some dummy ALProjects (Please ping if needed) We're still blocked on signing our apps as part of the pipelines using the native ALOps steps...

**Comment by AdminHodor** [comment] 2021-01-21 15:43
Dear @fvet ,

Could you please check this in our latest release v1.438 ?

Kind regards

**Comment by jcoe-nvt** [comment] 2021-01-21 15:51
@AdminHodor As member of @fvet team, I can confirm that this seems to be fixed.

**Closed** 2021-01-21 15:55 UTC
Labels: released
