### ISSUE TITLE
Microsoft.Dynamics.Nav.Management.NavAdminLogger error

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#433] opened 2021-10-01 05:53 UTC
**Describe the bug**
This morning all our release pipelines, deploying to BC17 environments, failed with the same error:

```
2021-10-01T04:08:06.1316908Z ##[error]The type initializer for 'Microsoft.Dynamics.Nav.Management.NavAdminLogger' threw an exception.
```

As it is 1st of October and MS has released BC19, it made me think this all is related. And indeed, probably, as the pipeline now is using a BC19 artifacts:

```
2021-10-01T04:08:04.4021848Z Name                           Value                                                                                   
2021-10-01T04:08:04.4023684Z ----                           -----                                                                                   
2021-10-01T04:08:04.4025474Z select                         Latest                                                                                  
2021-10-01T04:08:04.4027332Z type                           OnPrem                                                                                  
2021-10-01T04:08:04.4030439Z country                        W1                                                                                      
2021-10-01T04:08:04.4031327Z 
2021-10-01T04:08:04.4031663Z 
2021-10-01T04:08:04.4032582Z  -select: Latest -type: OnPrem -country: W1
2021-10-01T04:08:05.9203057Z *** Platform: C:\bcartifacts.cache\onprem\19.0.29894.30693\platform
2021-10-01T04:08:05.9264025Z *** Localisation: C:\bcartifacts.cache\onprem\19.0.29894.30693\w1
2021-10-01T04:08:05.9477994Z *** BC Management DLL: C:\bcartifacts.cache\onprem\19.0.29894.30693\platform\LegacyDlls\program files\Microsoft Dynamics NAV\190\RoleTailored Client\Microsoft.Dynamics.Nav.Management.dll
2021-10-01T04:08:05.9778506Z *** BC App Management DLL: C:\bcartifacts.cache\onprem\19.0.29894.30693\platform\LegacyDlls\program files\Microsoft Dynamics NAV\190\RoleTailored Client\Microsoft.Dynamics.Nav.Apps.Management.dll
```

Is there a way we can force it to use BC17 or BC18 artifacts? The **Batch Publish** task does not seem to provide that options.

Maybe this is related to #368.

**Comment by Arthurvdv** [comment] 2021-10-01 06:34
Same issue here

```
2021-10-01T05:59:24.2807486Z ##[section]Starting: ALOps Extension API
2021-10-01T05:59:24.2916060Z ==============================================================================
2021-10-01T05:59:24.2916356Z Task         : ALOps Extension API
2021-10-01T05:59:24.2916574Z Description  : Get/Publish extensions with the Business Central API
2021-10-01T05:59:24.2916781Z Version      : 1.445.2623
2021-10-01T05:59:24.2916951Z Author       : Hodor
2021-10-01T05:59:24.2917692Z Help         : Get/Publish extensions with the Business Central API.
2021-10-01T05:59:24.2917973Z ==============================================================================
2021-10-01T05:59:25.3365782Z *** Validate configuration
2021-10-01T05:59:25.6059494Z *** Task Inputs:
2021-10-01T05:59:25.6087412Z 
2021-10-01T05:59:25.6144226Z name                                                                                                             value
2021-10-01T05:59:25.6145974Z ----                                                                                                             -----
2021-10-01T05:59:25.6146960Z usedocker                                                                                                        False
2021-10-01T05:59:25.6148770Z fixed_tag                                                                                                             
2021-10-01T05:59:25.6150805Z interaction                                                                                                    publish
2021-10-01T05:59:25.6151694Z api_endpoint            https://api.businesscentral.dynamics.com/v2.0/***/Sandbox/api
2021-10-01T05:59:25.6153731Z apiversion                                                                                                        v1.0
2021-10-01T05:59:25.6154093Z authentication                                                                                                   oauth
2021-10-01T05:59:25.6155999Z azure_tenant_id                                                                   ***
2021-10-01T05:59:25.6156511Z azure_app_client_id                                                               ***
2021-10-01T05:59:25.6157808Z azure_app_client_secret                                                             ***
2021-10-01T05:59:25.6159484Z username                                                                                                              
2021-10-01T05:59:25.6160251Z password                                                                                                              
2021-10-01T05:59:25.6161712Z bccompany                                                                                                             
2021-10-01T05:59:25.6162216Z artifact_path                                                                    C:\azure-vsts-agent-deploy\_work\r2\a
2021-10-01T05:59:25.6163635Z artifact_filter                                                                                                  *.app
2021-10-01T05:59:25.6164086Z showdeploymentstatus                                                                                              True
2021-10-01T05:59:25.6164256Z 
2021-10-01T05:59:25.6176775Z 
2021-10-01T05:59:25.6181923Z 
2021-10-01T05:59:25.6282949Z *** For documentation, please visit   : https://www.alops.be/documentation
2021-10-01T05:59:25.6286483Z 
2021-10-01T05:59:25.9386807Z *** ALOps License:
2021-10-01T05:59:25.9397608Z   * Licensed To: Van Roey (Collection License)
2021-10-01T05:59:25.9400428Z 
2021-10-01T05:59:26.6009600Z *** Imported required PS-Functions
2021-10-01T05:59:26.6019087Z *** Parse Task Parameters
2021-10-01T05:59:26.6177173Z *** Creating API Connector with endpoint [https://api.businesscentral.dynamics.com/v2.0/***/Sandbox/api]
2021-10-01T05:59:26.6294358Z *** API Version: v1.0
2021-10-01T05:59:26.6307927Z *** Interaction Mode: publish
2021-10-01T05:59:26.6328749Z *** API Authentication: Using Azure OAuth Authentication []
2021-10-01T05:59:26.6343589Z *** Get OAuth token for tenant [***]
2021-10-01T05:59:26.6378279Z *** Communication: Service-2-Service
2021-10-01T05:59:26.6397185Z ##[command]Invoke-RestMethod -Method Post -Uri "https://login.microsoftonline.com/***/oauth2/token"
2021-10-01T05:59:26.9071962Z *** List Companies
2021-10-01T05:59:26.9120963Z ##[command]Invoke-RestMethod -Method Get -Uri 'https://api.businesscentral.dynamics.com/v2.0/***/sandbox/api/microsoft/automation/v1.0/companies'
2021-10-01T05:59:29.6534377Z 
2021-10-01T05:59:29.6540726Z 
2021-10-01T05:59:29.6548351Z id                : ac8a1700-641d-ea11-bb2f-000d3a2c3bc6
2021-10-01T05:59:29.6548634Z systemVersion     : 18.5.29545.0
2021-10-01T05:59:29.6550504Z name              : CRONUS BE
2021-10-01T05:59:29.6550728Z displayName       : Cronus BE
2021-10-01T05:59:29.6551636Z businessProfileId : 
2021-10-01T05:59:29.6553676Z systemCreatedAt   : 0001-01-01T00:00:00Z
2021-10-01T05:59:29.6554316Z systemCreatedBy   : 00000000-0000-0000-0000-000000000000
2021-10-01T05:59:29.6554535Z systemModifiedAt  : 2021-02-25T08:56:33.657Z
2021-10-01T05:59:29.6554936Z systemModifiedBy  : 222eea85-e95a-4df2-b54f-b6247110e61d
2021-10-01T05:59:29.6555295Z 
< ......... >
2021-10-01T05:59:29.6583093Z 
2021-10-01T05:59:29.6583293Z 
2021-10-01T05:59:29.6584201Z 
2021-10-01T05:59:29.6607253Z *** Selected Company: CRONUS BE [ac8a1700-641d-ea11-bb2f-000d3a2c3bc6]
2021-10-01T05:59:29.6676355Z ##[command]Invoke-RestMethod -Method Get -Uri 'https://api.businesscentral.dynamics.com/v2.0/***/sandbox/api/microsoft/automation/v1.0/companies(ac8a1700-641d-ea11-bb2f-000d3a2c3bc6)/extensions'
2021-10-01T05:59:30.0590301Z *** Installed Extensions:
2021-10-01T05:59:30.0627933Z 
2021-10-01T05:59:30.0962637Z publisher         displayName                                              version id                                  
2021-10-01T05:59:30.0964534Z ---------         -----------                                              ------- --                                  
2021-10-01T05:59:30.0966547Z Continia Software Continia Core                                            4.1     4b915d7e-c02a-435f-85ab-649086c1e002
2021-10-01T05:59:30.0969099Z Continia Software Continia Delivery Network                                1.1     0745e76d-0b72-4641-87c2-ee45db5d2c32
2021-10-01T05:59:30.0971224Z Continia Software Continia Document Capture 365                            7.1     6da8dd2f-e698-461f-9147-8e404244dd85
2021-10-01T05:59:30.0973535Z ForNAV            Customizable Report Pack                                 6.0     83326d6d-11f8-49fd-981a-6f266a7c8d81
2021-10-01T05:59:30.0974893Z ForNAV            ForNAV Core                                              6.0     6f0293d3-86fc-4ff8-9632-54a580be6546
2021-10-01T05:59:30.0976226Z ForNAV            ForNAV Language Module                                   6.0     f94c6dff-0118-4c1d-a7d4-382033529ed3
2021-10-01T05:59:30.0977957Z Microsoft         AMC Banking 365 Fundamentals                             18.5    16319982-4995-4fb1-8fb2-2b1e13773e3b
2021-10-01T05:59:30.0979166Z Microsoft         Application                                              18.5    c1335042-3002-4257-bf8a-75c898ccb1b8
2021-10-01T05:59:30.0980427Z Microsoft         Base Application                                         18.5    437dbf0e-84ff-417a-965d-ed2bb9650972
2021-10-01T05:59:30.0981785Z Microsoft         Business Central Cloud Migration - Previous Release      18.5    6992416f-3f39-4d3c-8242-3fff61350bea
2021-10-01T05:59:30.0983229Z Microsoft         Business Central Cloud Migration - Previous Release (BE) 18.5    620725d3-2ed5-424a-bd9b-7d4b44bfcc9b
2021-10-01T05:59:30.0984705Z Microsoft         Business Central Intelligent Cloud                       18.5    334ef79e-547e-4631-8ba1-7a7f18e14de6
2021-10-01T05:59:30.0986178Z Microsoft         Company Hub                                              18.5    c512d720-63b9-4b26-b062-a0c09b4ed322
2021-10-01T05:59:30.0987468Z Microsoft         Email - Current User Connector                           18.5    08d69832-9231-429e-be2c-8bab2c96905b
2021-10-01T05:59:30.0988717Z Microsoft         Email - Microsoft 365 Connector                          18.5    aceb66c8-472e-437c-81d3-27e6c07d0f14
2021-10-01T05:59:30.0989971Z Microsoft         Email - Outlook REST API                                 18.5    e6328152-bb29-4664-9dae-3bc7eaae1fd8
2021-10-01T05:59:30.0991198Z Microsoft         Email - SMTP Connector                                   18.5    68e13fa3-217a-4be0-9141-99e5bf0ca818
2021-10-01T05:59:30.0992439Z Microsoft         Essential Business Headlines                             18.5    2a89f298-7ffd-44a5-a7ce-e08dac98abce
2021-10-01T05:59:30.0993690Z Microsoft         Intelligent Cloud Base                                   18.5    58623bfa-0559-4bc2-ae1c-0979c29fd9e0
2021-10-01T05:59:30.0994953Z Microsoft         Late Payment Prediction                                  18.5    3d5b2137-efeb-4014-8489-41d37f8fd4c3
2021-10-01T05:59:30.0996186Z Microsoft         PayPal Payments Standard                                 18.5    d09fa965-9a2a-424d-b704-69f3b54ed0ce
2021-10-01T05:59:30.0997444Z Microsoft         Sales and Inventory Forecast                             18.5    c526b3e9-b8ca-4683-81ba-fcd5f6b1472a
2021-10-01T05:59:30.0998723Z Microsoft         Send To Email Printer                                    18.5    8c972578-fe72-4aa5-ae51-cc5575fef2ea
2021-10-01T05:59:30.0999990Z Microsoft         Simplified Bank Statement Import                         18.5    79b1a79a-2f66-4736-bc1b-8abb3537eb51
2021-10-01T05:59:30.1001270Z Microsoft         System Application                                       18.5    63ca2fa4-4f03-4f2b-a480-172fef340d3f
2021-10-01T05:59:30.1002642Z Microsoft         Universal Print Integration (Preview)                    18.5    2654d7e7-9afd-4947-9e02-6bb8f3e0cd04
2021-10-01T05:59:30.1003831Z Microsoft         VAT Group Management                                     18.5    c50a4bf0-db51-4ad2-88d5-fe2287da0eb8
2021-10-01T05:59:30.1005034Z Microsoft         WorldPay Payments Standard                               18.5    bae453ed-0fd8-4416-afdc-4b09db6c12c3
2021-10-01T05:59:30.1006590Z Red and Bundle    Multiple Report Layout Selector                          2.1     31e6154c-7bb5-4d51-a415-ccf39e06043f
2021-10-01T05:59:30.1008420Z VanRoey.be        Connection Library                                       1.0     f6c1bb7c-8873-4537-86a9-7c423c3048f6
2021-10-01T05:59:30.1009659Z VanRoey.be        Customer - D365BC Extension                          2.0     22b42e4f-a408-402e-90a1-2ebe2f331a59
2021-10-01T05:59:30.1010898Z VanRoey.be        Finance Extension (BE)                                   1.0     c7f3afeb-95cc-4ffe-8c3c-6c1ac185e864
2021-10-01T05:59:30.1012239Z VanRoey.be        Finance Extension Library                                1.0     b561d731-1e39-4bf4-a2ea-a162f3ab38a8
2021-10-01T05:59:30.1012416Z 
2021-10-01T05:59:30.1013312Z 
2021-10-01T05:59:30.1016435Z 
2021-10-01T05:59:30.1019906Z *** Published Extensions (not installed):
2021-10-01T05:59:30.1029907Z 
2021-10-01T05:59:30.1040932Z publisher  displayName                     version id                                  
2021-10-01T05:59:30.1043206Z ---------  -----------                     ------- --                                  
2021-10-01T05:59:30.1045267Z VanRoey.be Customer - D365BC Extension 2.0     22b42e4f-a408-402e-90a1-2ebe2f331a59
2021-10-01T05:59:30.1046610Z VanRoey.be Customer - D365BC Extension 2.0     22b42e4f-a408-402e-90a1-2ebe2f331a59
2021-10-01T05:59:30.1047803Z VanRoey.be Customer - D365BC Extension 2.0     22b42e4f-a408-402e-90a1-2ebe2f331a59
2021-10-01T05:59:30.1049036Z VanRoey.be Customer - D365BC Extension 2.0     22b42e4f-a408-402e-90a1-2ebe2f331a59
2021-10-01T05:59:30.1049200Z 
2021-10-01T05:59:30.1049766Z 
2021-10-01T05:59:30.1052230Z 
2021-10-01T05:59:30.1071307Z *** Import NAV/BC Management DLL's
2021-10-01T05:59:30.1083831Z *** ServiceTier not specified, loading default assemblies.
2021-10-01T05:59:30.1114461Z *** Default Assemblies not found. Load via BC-Artifacts
2021-10-01T05:59:30.1141554Z *** Install/Update BCContainerHelper [https://github.com/microsoft/navcontainerhelper]
2021-10-01T05:59:30.1162676Z *** Check BcContainerHelper
2021-10-01T05:59:30.1553581Z *** Load BcContainerHelper
2021-10-01T05:59:30.2643819Z BcContainerHelper version 2.0.16
2021-10-01T05:59:30.8601883Z 
2021-10-01T05:59:30.8602379Z ModuleType Version    Name                                ExportedCommands                                             
2021-10-01T05:59:30.8602992Z ---------- -------    ----                                ----------------                                             
2021-10-01T05:59:30.8603654Z Script     2.0.16     BcContainerHelper                   {Add-FontsToBcContainer, Add-GitToAlProjectFolder, Backup-...
2021-10-01T05:59:30.8603800Z 
2021-10-01T05:59:30.8603873Z 
2021-10-01T05:59:30.8603924Z 
2021-10-01T05:59:30.8605984Z 
2021-10-01T05:59:30.8624864Z ##[command]"Get-BCArtifactUrl" 
2021-10-01T05:59:30.8625324Z Name                           Value                                                                                   
2021-10-01T05:59:30.8626022Z ----                           -----                                                                                   
2021-10-01T05:59:30.8626558Z select                         Latest                                                                                  
2021-10-01T05:59:30.8627030Z type                           OnPrem                                                                                  
2021-10-01T05:59:30.8627349Z country                        W1                                                                                      
2021-10-01T05:59:30.8627491Z 
2021-10-01T05:59:30.8627584Z 
2021-10-01T05:59:30.8627740Z  -select: Latest -type: OnPrem -country: W1
2021-10-01T05:59:32.5753255Z Downloading application artifact /onprem/19.0.29894.30693/w1
2021-10-01T05:59:32.5862612Z Downloading C:\Windows\TEMP\7f87c0f8-74de-4d7f-8270-e8a53076cb29.zip
2021-10-01T05:59:38.1922701Z Unpacking application artifact to tmp folder using Expand-Archive
2021-10-01T05:59:40.0964667Z Downloading platform artifact /onprem/19.0.29894.30693/platform
2021-10-01T05:59:40.0977611Z Downloading C:\Windows\TEMP\e380df2b-ef47-46a0-90e5-2d79cd7f7dfc.zip
2021-10-01T06:00:06.6193220Z Unpacking platform artifact to tmp folder using Expand-Archive
2021-10-01T06:00:42.8544166Z Downloading Prerequisite Components
2021-10-01T06:00:42.8602312Z Downloading C:\bcartifacts.cache\onprem\19.0.29894.30693\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
2021-10-01T06:00:46.9825030Z Downloading C:\bcartifacts.cache\onprem\19.0.29894.30693\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
2021-10-01T06:00:47.0947594Z Downloading C:\bcartifacts.cache\onprem\19.0.29894.30693\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
2021-10-01T06:00:47.3957233Z *** Platform: C:\bcartifacts.cache\onprem\19.0.29894.30693\platform
2021-10-01T06:00:47.3972098Z *** Localisation: C:\bcartifacts.cache\onprem\19.0.29894.30693\w1
2021-10-01T06:00:47.4130659Z *** BC Management DLL: C:\bcartifacts.cache\onprem\19.0.29894.30693\platform\LegacyDlls\program files\Microsoft Dynamics NAV\190\RoleTailored Client\Microsoft.Dynamics.Nav.Management.dll
2021-10-01T06:00:47.4372952Z *** BC App Management DLL: C:\bcartifacts.cache\onprem\19.0.29894.30693\platform\LegacyDlls\program files\Microsoft Dynamics NAV\190\RoleTailored Client\Microsoft.Dynamics.Nav.Apps.Management.dll
2021-10-01T06:00:47.4470073Z *** Publish Extension
2021-10-01T06:00:47.4476359Z   * Artifact Path  : C:\azure-vsts-agent-deploy\_work\r2\a
2021-10-01T06:00:47.4482303Z   * Artifact Filter: *.app
2021-10-01T06:00:47.4586987Z *** Resolve App file in [C:\azure-vsts-agent-deploy\_work\r2\a]
2021-10-01T06:00:47.4633570Z *** Resolved App File: [C:\azure-vsts-agent-deploy\_work\r2\a\App\Customer\VanRoey.be_Customer - D365BC Extension_2.0.18787.0_sandbox_18.5_be.app].
2021-10-01T06:00:47.4646803Z *** Resolved App Path: [C:\azure-vsts-agent-deploy\_work\r2\a\App\Customer\VanRoey.be_Customer - D365BC Extension_2.0.18787.0_sandbox_18.5_be.app]
2021-10-01T06:00:47.4691371Z *** Upload extension [C:\azure-vsts-agent-deploy\_work\r2\a\App\Customer\VanRoey.be_Customer - D365BC Extension_2.0.18787.0_sandbox_18.5_be.app]
2021-10-01T06:00:47.4697463Z *** Get App Info
2021-10-01T06:00:47.5584938Z ##[error]The type initializer for 'Microsoft.Dynamics.Nav.Management.NavAdminLogger' threw an exception.
2021-10-01T06:00:47.5850996Z ##[section]Finishing: ALOps Extension API
```

**Comment by waldo1001** [comment] 2021-10-01 07:44
This is a bug in V19.  The problem is that there is a problem with the dlls in the "LegacyDlls" of the artifact-folders of the v19 release.

We found a fix though.. .  Will be deployed soon!

**Comment by acjdekorte** [comment] 2021-10-01 12:39
@waldo1001 Could you provide an update, when the fix will be deployed?

**Comment by acjdekorte** [comment] 2021-10-01 12:51
I see that version 1.445.2647 just came available. This is solving our problem.

**Comment by waldo1001** [comment] 2021-10-01 13:48
@lvanvugt , @acjdekorte , @Arthurvdv ,

The fix is indeed live - thanks for confirming it solves the problem.

**Closed by waldo1001** 2021-10-01 13:48 UTC

**Comment by Arthurvdv** [comment] 2021-10-02 08:37
@waldo1001, thank you for the quick fix!

**Comment by lvanvugt** [comment] 2021-10-02 08:42
Thanx form me 2.

**Comment by acjdekorte** [comment] 2021-10-02 10:45
Thank you

**Comment by waldo1001** [comment] 2021-10-04 07:15
Very welcome ;-)
