### ISSUE TITLE
Issue with ALOps Import FOB & Schema Sync

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#90] opened 2020-02-26 15:30 UTC
Hey Guys, 

I am facing another issue in relation ALOPS Import FOB command. It did run & imported all needed objects, but schema synchronization did not occur. ServerInstance remained on SyncPending state after object import. 

- Agent is installed on the same VM where NAV instance is running and it's full access to it. 
- SQL server is hosted on AzureSQL. (Suprisingly ALOps figures out user name & password parameters)
- Log folder contains only one file 'navcommandresult.txt' with successful message within. No other log files were generated.
- Running schema sync manually did not produce any errors (there's no breaking changes)
- if you look close to the command properties, you will see **ServerName** there twice. Perhaps that's the issue?

```
*** FOB File filter: C:\agent\_work\r1\a\_Release_CI\mv_Release_CI_35175_master\Release_CI_35175.fob
*** Import Action: Overwrite
*** Start processing FOB: [Release_CI_35175.fob]
*** Import FOB: [Release_CI_35175.fob] in [NAV]
  * DatabaseServer   : azuresqlserver.database.windows.net
  * Database Instance: 
  * Database Name    : MV8BAT
  * Management Port  : 7045
*** Running command: & "C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\finsql.exe" --% Command=ImportObjects,ImportAction=Overwrite,SynchronizeSchemaChanges=Yes,File="C:\agent\_work\r1\a\_Release_CI\mv_Release_CI_35175_master\Release_CI_35175.fob",LogFile="C:\Users\nadmin\AppData\Local\Temp\NavIde\cefd65f6-8fbb-45d4-bb03-8a2cbb480153\Release_CI_35175.log",ntauthentication=No,username="nadmin",password="*****",ServerName="",generatesymbolreference=0,ServerName="azuresqlserver.database.windows.net",Database="MV8BAT",NavServerName="localhost",NavServerInstance="NAV",NavServerManagementport=7045 | Out-Null
```

**Comment by waldo1001** [comment] 2020-03-02 11:54
Probably the double servername is the reason - we will look at it asap!

**Comment by waldo1001** [comment] 2020-03-03 15:31
I think this is the unfortunate result of a windows update.  Freddy blogged about it here:
https://freddysblog.com/2020/02/26/the-world-after-february-18th/

Could you please either try to run "hyperv" isolation mode?  You can do that by:
![image](https://user-images.githubusercontent.com/12088142/75776724-d3301080-5d54-11ea-820f-8149840fbd88.png).  

If this works - I would go for a more preferred setup:
- revert the february Windows update 
- disable automatic updates on servers with DevOps agents to prevent unexpected things like this.
- disable "hyperv" isolation again to use process isolation

**Comment by gintuoklis** [comment] 2020-03-03 15:44
hey waldo, 
i am not using docker in this case. I'm importing it to NAV instance.

this is my task code:
```
steps:
- task: Hodor.hodor-alops.alopsfobimport.ALOpsFobImport@1
  displayName: 'ALOps Import FOB'
  inputs:
    nav_serverinstance: NAV
    filePath: '$(System.DefaultWorkingDirectory)/_Release_CI/**/Release_CI_*.fob'
    import_action: Overwrite
```

**Comment by waldo1001** [comment] 2020-03-04 09:51
Still - can you try to roll back february update?

**Comment by gintuoklis** [comment] 2020-03-04 10:47
the server we run installation is running this OS version.
![image](https://user-images.githubusercontent.com/16342128/75872029-6032a280-5e05-11ea-85ef-b2dd194aa598.png)
Like i mentioned before, docker is not used there. We just run object import. 
I have no possibility of uninstalling on that machine. 
Will try to test with other environments too

**Comment by waldo1001** [comment] 2020-03-04 10:59
I know docker is not used .. but the feb update has a problem with 32-bit executables, like finsql.exe .. so we need to check if that update (I think it's KB4532691) is the root cause of this issue :-/.

We have a number of build pipelines that check this every day, so we're not able to replicate it :-/

**Comment by waldo1001** [comment] 2020-03-04 14:11
Can you also provide the complete log?

**Comment by gintuoklis** [comment] 2020-03-10 09:09
We tested it again on two different environments. Result is the same. Objects imported successfully, but instance stays on SyncPending state. Running Sync-NAVtenant brings it to operational. (no errors or whatsoever)

Will try to replicate the scenario with the smaller fob and provide you with more details. Now, we are importing fob with 10k objects, which takes a while.

**Comment by waldo1001** [comment] 2020-03-10 09:50
So .. it's "solveable" when you add the step to Sync-NAVTenant with the step "ALOpsDockerExec"?

We'll try to make it more stable, but we're very dependent on the 32-bit finsql, here, I'm afraid :(.

**Comment by gintuoklis** [comment] 2020-03-10 09:59
Cnanot use ALOpsDockerExec. It works with docker only. In our case, we are not using it. 
I just need to script it out (load nav admin module, and run Sync-NAVTenant)

**Comment by waldo1001** [comment] 2020-03-10 12:20
Right - that's also possible :-).
sorry ..

**Comment by waldo1001** [comment] 2020-09-15 21:20
I'll close this issue - you can reopen when necessary.

**Closed by waldo1001** 2020-09-15 21:20 UTC
Labels: investigate
